#Spacing is extremly important
guru:
  jms:
    username: JMS Username
    password: ymlpassword
    dburl: ymldburl

#file separation
---
#specific properties for a profile
spring:
  profiles: de
guru:
  jms:
    username: JMS Username GERMAN